name: .NET Core build AvaDevBox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore Src/AvaDevBox.sln
    - name: Build
      run: |
		dotnet build --configuration Release --no-restore  ./AvaDevBox/AvaDevBox.csproj
		dotnet build --configuration Release --no-restore  ./AvaDevBox.Themes.Default/AvaDevBox.Themes.Default.csproj
		dotnet build --configuration Release --no-restore  ./AvaloniaControlTest/AvaloniaControlTest.csproj
      working-directory: Src
	  
    # - name: Test
      # run: dotnet test --no-restore --verbosity normal Src/AvaDevBox.sln
